### ISSUE TITLE
[Question] How to read battery level

### ISSUE THREAD

**Issue by bit-user** [imperfectpython/bbq-hacking-part-3#1]
First off, I really enjoyed your videos and the explanations are just great :)

I tried to read the battery level from the sensor, but it doesn't seem to work- do you have any idea how that's done?

I tried the following:
battery_level = bytearray( [ 0x08, 0x24, 0x00, 0x00, 0x00, 0x00 ] )
device.char_write_handle(0x0029, connection_key)
device.char_write_handle(0x0034, enable_notifications)
device.char_write_handle(0x0034, battery_level)

Then I subscribed to f4:
device.subscribe("0000fff4-0000-1000-8000-00805f9b34fb", callback=handle_notifications)

But I also tried to write to 0x0035 and then subscribe to f5:
device.char_write_handle(0x0035, battery_level)
device.subscribe("0000fff4-0000-1000-8000-00805f9b34fb", callback=handle_notifications)

Nothing worked...I am not receiving any battery level messages.

Do you have any clue here? :)

Thanks!

**Comment by imperfectpython** [comment]
Thanks @bit-user glad you enjoyed the videos! 

Getting battery level data is a little more complicated due to how the information is stored. I decided not to capture/process this data, but have looked around on GitHub and came across a few projects that discuss how it is stored/transmitted that may be of interest.
 
Both of the programs below start by doing a char_write_handle to 0x0034 with the battery_level byte_array like you did in the first part of your code to enable battery notifications. After that you'll want to do a `device.subscribe("0000fff1-0000-1000-8000-00805f9b34fb", callback=handle_battery)`

The battery data comes by subscribing to _**fff1**_ and then we will need to create a new callback function called _handle_battery_ since the data will need to be processed differently than the temperature data notifications. See the Python "battery_level" function used [here](https://github.com/adafruit/Adafruit_CircuitPython_BLE_iBBQ/blob/8a048b9f5af3d8cefb8d8dcee88e76bbd61e2276/adafruit_ble_ibbq.py#L180) for an idea of how to process and handle the battery notification. It has to be calculated based on current and max voltage values.

Python Project: (https://github.com/adafruit/Adafruit_CircuitPython_BLE_iBBQ/blob/8a048b9f5af3d8cefb8d8dcee88e76bbd61e2276/adafruit_ble_ibbq.py#L166) 
Another example of reading battery level data written in Golang: https://github.com/sworisbreathing/go-ibbq/blob/a8933daef2744ee5d26d0dba77c8c5028292b3e8/ibbq.go#L251

Hope this helps!

**Comment by bit-user** [comment]
Ah, you are amazing! That really did the trick (plus waiting for 30 seconds or so to receive the message, because you only receive a message on a change of the battery^^).

Thanks a lot! And keep up the good work :)
